FROM node:14.14.0-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
# Copy command is not necessary because in docker compose we attach the files to the folder out side the container
#but is necesary to run in travis because the files are not present
COPY --chown=node:node ./ ./
 
CMD ["npm", "run", "dev"]